language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "bayar4b" # the key of the org you chose at step #3
    token:
      secure: "ss3LDnLL+9gyVNsjc5VCZlVeV4KpcU/aU88HxSG0xXS1KDExUbsY0brkH5AayLenkugBKIf8g7b6wHTH/4PM6XlPZFgBAOQs58y3irZw93sc74vZUE1Bsqa1sVgBcA9NEU693cZmkZ5bs8WKhNf4Ec7FCaxxvx2EuX9aE053NWt+RaYo0qHh8EX9ZDLBegYfGS/o6bumH1jX4RjJseOakQr3vs+LHxhkodQ6+6CqusiK8t/ZIXeWCbHKvCOcZ/X+iEGaG3d4MQNchwM5WasVQ25Y8807o5ePW3QWnGiNBrs7G1HYvwWYEWDRyzm1NhHlPPp/X0WGhj/CvAZWP6Wi2b8rJoQfkUoI+aHM7oPJl+UJryUsJ4bMtWy7w+Ylk19ZF7Y5m6RZbMqFA7ykmK0kWQDk1dziJqMCWXEp6qqCTF3r69J/gLMAAi5othiwdPYDY7KCDiS48vsgsNUjFk7+gsmpzOide1wKl0C1dey2zLcKSq+9J0PgOO+Q84kL+cduN8FJv5tjPlzc7q1TI4DB3iHAwXvyLnA89fNRSw5AP0x1eLCdCo7zt9jgyVjdY2TYeAGASgCaxMG6icPq5WLcDzMpRE5TM/NeVekGwpyiR4LaJPZHCJpRLGvBKPpNkrc+cLiqOcjNokv3Muitc6OnYQwJahI0TnhM/3wgkmmB6Zo="

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "bayar4b"
      - echo "BBaya2014" | docker login --username "bayar4b" --password-stdin
      - docker tag unige/api-gateway bayar4b/api-gateway:latest
      - docker tag unige/regulatory-service bayar4b/regulatory-service:latest
      - docker tag unige/valuation-service bayar4b/valuation-service:latest
      - docker tag unige/instrument-service bayar4b/instrument-service:latest
      - docker tag unige/counterparty-service bayar4b/counterparty-service:latest     
      - docker push bayar4b/api-gateway:latest
      - docker push bayar4b/regulatory-service:latest
      - docker push bayar4b/valuation-service:latest
      - docker push bayar4b/instrument-service:latest
      - docker push bayar4b/counterparty-service:latest
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Bayar4B_microservices
      # - mvn sonar:sonar -Dsonar.projectKey=Bayar4B_microservices -Dsonar.organization=bayar4b -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=10de2947edc0e089a82360cb2d1aa97482fafc28     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "BBaya2014" | docker login -u "bayar4b" --password-stdin      
      - docker tag unige/web-ui bayar4b/web-ui:latest      
      - docker push bayar4b/web-ui:latest
