language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "bayar4b" # the key of the org you chose at step #3
    token: 
      secure: "rSDHoc793154lmprGXtfpkm9+eismVu+R1+c4OKPec7ed8cG7iojSiGwhmJqLG2ntRfLS88xNWjGWSicoYZAddM/DNLy0TCQStaMbV/BFE8/9AkflZZjBuTMRt4I3TOe44fo8m6w2MddqePZlDtDtZFoGD+nIIRHMKw1+6S9hb7Bw6CLFEjruiO/Fd68CF/nkuz8Jo77obMudyGxnKX9z7M25fzjFFzuNqDMjzgSECbkC4vl7HcGNw7/AWJzbDBIzIE8aEFJD0S/jPS+o4+gwdgVqatlfAyQ8KgWah6IWom17nCQvW/240tJVjKXFXHGGxmL0ZsTLdCF9vwU4kiippxz008bud32atU8WLJOcSkbAHtlVHDh0NtfyJG3L5/PziqF/bptWByjn9XcBwLLQcanHE6Tux6XkpPXO2vZhA+HVp7SdSHwhZe1sIftut4wWDEsyTsF+Kb3NPK91B9hXbQXCnvaPLwvMQn1pVXuiI+B73FUWvmaYxhF3JKL374klqBsYvYP8iXYMYWL8G65IAW60NlC8o85lYZz23HwQQ9TUrzakOzbUseDYfBJLmhPYBjJbQovixzRcSAKqXFX6dNSxn6fxmLBWlwjz+fzU2rtOPFXCN7/Bis5j6lJme0cuIY/XhtDVqaTKEtn52B+LuubVcVoWs+P5HLLVNAuUHg="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Bayar4B_microservices

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules

jobs:
  include:
    - stage: Prepare
      script:
      - nvm install $NODE_VERSION
      - mvn install -N -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage : Build
      script:
      - mvn install -Ppackage-docker-image  
      - echo "bayar4b"
      - echo "$DOCKER_PASSWORD" | docker login --username "bayar4b" --password-stdin
      - docker tag unige/api-gateway bayar4b/api-gateway:latest
      - docker tag unige/regulatory-service bayar4b/regulatory-service:latest
      - docker tag unige/valuation-service bayar4b/valuation-service:latest
      - docker tag unige/instrument-service bayar4b/instrument-service:latest
      - docker tag unige/counterparty-service bayar4b/counterparty-service:latest     
      - docker push bayar4b/api-gateway:latest
      - docker push bayar4b/regulatory-service:latest
      - docker push bayar4b/valuation-service:latest
      - docker push bayar4b/instrument-service:latest
      - docker push bayar4b/counterparty-service:latest
      - mvn sonar:sonar -Dsonar.projectKey=Bayar4B_microservices -Dsonar.organization=bayar4b -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=7147ce62b9daab44c83626f2b1f448386c220bb5     
    - stage : Build
      script:
      - cd web-ui
      - pwd
      - npm -v
      - npm install
      - npm update
      - npm run-script build --prod
      - docker build -t unige/web-ui .
      - echo "$DOCKER_PASSWORD" | docker login -u "bayar4b" --password-stdin      
      - docker tag unige/web-ui bayar4b/web-ui:latest      
      - docker push bayar4b/web-ui:latest
